apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard2-headless-service
  namespace: namespace
  labels:
    name: mongodb-shard2
spec:
  ports:
  - port: 27018
    targetPort: 27018
  selector:
    role: mongodb-shard2
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongodb-shard2
  namespace: namespace
spec:
  selector:
    matchLabels:
      role: mongodb-shard2 # has to match .spec.template.metadata.labels
  serviceName: mongodb-shard2-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-shard2
        tier: maindb
        replicaset: shard0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - shard0
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-shard2-container
          image: mongo:3.6
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--shardsvr"
            - "--replSet"
            - "shard0"
            - "--dbpath"
            - "/data/s2"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27018
          volumeMounts:
            - name: mongo-shard2-persistent-storage-claim
              mountPath: /data/s2
  volumeClaimTemplates:
  - metadata:
      name: mongo-shard2-persistent-storage-claim
      annotations:
         pv.kubernetes.io/bind-completed: "yes"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10
